// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ArdupilotmegaMessageFetchService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::mavlink::thrift;

class ArdupilotmegaMessageFetchServiceHandler : virtual public ArdupilotmegaMessageFetchServiceIf {
 public:
  ArdupilotmegaMessageFetchServiceHandler() {
    // Your initialization goes here
  }

  void availableMessages(std::map<ArdupilotmegaMessageTypes::type, int32_t> & _return) {
    // Your implementation goes here
    printf("availableMessages\n");
  }

  void fetchSensorOffsets(const std::vector<SensorOffsets> & msg) {
    // Your implementation goes here
    printf("fetchSensorOffsets\n");
  }

  void fetchSetMagOffsets(const std::vector<SetMagOffsets> & msg) {
    // Your implementation goes here
    printf("fetchSetMagOffsets\n");
  }

  void fetchMeminfo(const std::vector<Meminfo> & msg) {
    // Your implementation goes here
    printf("fetchMeminfo\n");
  }

  void fetchApAdc(const std::vector<ApAdc> & msg) {
    // Your implementation goes here
    printf("fetchApAdc\n");
  }

  void fetchDigicamConfigure(const std::vector<DigicamConfigure> & msg) {
    // Your implementation goes here
    printf("fetchDigicamConfigure\n");
  }

  void fetchDigicamControl(const std::vector<DigicamControl> & msg) {
    // Your implementation goes here
    printf("fetchDigicamControl\n");
  }

  void fetchMountConfigure(const std::vector<MountConfigure> & msg) {
    // Your implementation goes here
    printf("fetchMountConfigure\n");
  }

  void fetchMountControl(const std::vector<MountControl> & msg) {
    // Your implementation goes here
    printf("fetchMountControl\n");
  }

  void fetchMountStatus(const std::vector<MountStatus> & msg) {
    // Your implementation goes here
    printf("fetchMountStatus\n");
  }

  void fetchFencePoint(const std::vector<FencePoint> & msg) {
    // Your implementation goes here
    printf("fetchFencePoint\n");
  }

  void fetchFenceFetchPoint(const std::vector<FenceFetchPoint> & msg) {
    // Your implementation goes here
    printf("fetchFenceFetchPoint\n");
  }

  void fetchFenceStatus(const std::vector<FenceStatus> & msg) {
    // Your implementation goes here
    printf("fetchFenceStatus\n");
  }

  void fetchAhrs(const std::vector<Ahrs> & msg) {
    // Your implementation goes here
    printf("fetchAhrs\n");
  }

  void fetchSimstate(const std::vector<Simstate> & msg) {
    // Your implementation goes here
    printf("fetchSimstate\n");
  }

  void fetchHwstatus(const std::vector<Hwstatus> & msg) {
    // Your implementation goes here
    printf("fetchHwstatus\n");
  }

  void fetchRadio(const std::vector<Radio> & msg) {
    // Your implementation goes here
    printf("fetchRadio\n");
  }

  void fetchLimitsStatus(const std::vector<LimitsStatus> & msg) {
    // Your implementation goes here
    printf("fetchLimitsStatus\n");
  }

  void fetchWind(const std::vector<Wind> & msg) {
    // Your implementation goes here
    printf("fetchWind\n");
  }

  void fetchData16(const std::vector<Data16> & msg) {
    // Your implementation goes here
    printf("fetchData16\n");
  }

  void fetchData32(const std::vector<Data32> & msg) {
    // Your implementation goes here
    printf("fetchData32\n");
  }

  void fetchData64(const std::vector<Data64> & msg) {
    // Your implementation goes here
    printf("fetchData64\n");
  }

  void fetchData96(const std::vector<Data96> & msg) {
    // Your implementation goes here
    printf("fetchData96\n");
  }

  void fetchRangefinder(const std::vector<Rangefinder> & msg) {
    // Your implementation goes here
    printf("fetchRangefinder\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ArdupilotmegaMessageFetchServiceHandler> handler(new ArdupilotmegaMessageFetchServiceHandler());
  shared_ptr<TProcessor> processor(new ArdupilotmegaMessageFetchServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

