/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ardupilotmega_CONSTANTS_H
#define ardupilotmega_CONSTANTS_H

#include "ardupilotmega_types.h"

namespace mavlink { namespace thrift {

class ardupilotmegaConstants {
 public:
  ardupilotmegaConstants();

};

extern const ardupilotmegaConstants g_ardupilotmega_constants;

}} // namespace

#endif
