/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ardupilotmega_constants.h"

namespace mavlink { namespace thrift {

const ardupilotmegaConstants g_ardupilotmega_constants;

ardupilotmegaConstants::ardupilotmegaConstants() {
}

}} // namespace

